### ISSUE TITLE
Настроить GitHub actions

### ISSUE THREAD

**Issue by PeachMood** [MostBridge/Frontend#1]
Подготовить проект для CI и добавить автоматический запуск GiHub Runners в Pull Request:

1. Добавить eslint
2. Прописать workflow

**Comment by marylaf** [comment]
<img width="1068" alt="image" src="https://github.com/MostBridge/Frontend/assets/103425086/dda77782-53d0-426e-9c4a-5fce2cc02e8f">

**Comment by marylaf** [comment]
1) у нас же есть eslint

**Comment by PeachMood** [comment]
Я читала в спецификации vite, что eslint настраивать нужно отдельно. Однако, оказывается, eslint в нашем проекте действительно есть. Тем не менее я решила его немного расширить и добавила code style от Airbnb. Дефолтная конфигурация скорее корректность кода проверяла, чем код code style :)
