### ISSUE TITLE
Почистить проект

### ISSUE THREAD

**Issue by PeachMood** [MostBridge/Frontend#2]
1. Оформить index.html: title, description, keywords, team
2. Убрать лишние файлы, картинки, импорты, стили
3. Оставить в App.tsx пустой div

**Comment by marylaf** [comment]
я беру на себя

**Comment by marylaf** [comment]
1. Оформиkf index.html: title, description, keywords, author
2. Убрала лишние файлы, картинки, импорты, стили - но предлагаю глянуть еще кому-нибудь. 
3. Оформила App.tsx: роуты и тд
